In [5]:
import numpy as np
arr1 = np.array([1, 2, 3]) 
print(arr1)
arr2 = np.zeros((2,2))
print(arr2)
arr3 = np.ones((2,3))
print(arr3)
arr4 = np.arange(2,11,2)
print(arr4)
arr5 = np.linspace(5,10,5)
print(arr5)


[1 2 3]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[ 2  4  6  8 10]
[ 5.    6.25  7.5   8.75 10.  ]


In [69]:
#IMPORTANT ATTRIBUTES OF NUMPY ARRAY

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)#number of dimension
print(arr.shape)
print(arr.dtype)
print(arr.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int32
6


In [75]:
#Arithemetic Operation On Numpy Array
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 * a2)
print(a2 - a1)
print(a2 / a1)


[5 7 9]
[ 4 10 18]
[3 3 3]
[4.  2.5 2. ]


In [87]:
#INDEXING AND SLICING
a = np.array([10,20,30,40,50])
print(a[2])

print(a[1:4])
print(a[::-1])

30
[20 30 40]
[50 40 30 20 10]


In [390]:
a = np.array([[1,2,2],[4,5,6]])
print(a.reshape(3,2))
print(a.flatten())
print(a.ravel())


[[1 2]
 [2 4]
 [5 6]]
[1 2 2 4 5 6]
[1 2 2 4 5 6]


In [14]:
#CONCATENATE ARRAY
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

conc = np.concatenate((a,b),axis=0)
print(conc)
print('...............')
print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
...............
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])

split = np.split(a,3,axis=1)
print(split)

hsplit = np.hsplit(a,3)
print(hsplit)

# vsplit = np.vsplit(a,3)
# print(vsplit)





[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [169]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

reshape_a = a.reshape(2,2)
print(reshape_a)

reshape_b = b.reshape(2,2)
print('................')

concat = np.concatenate((reshape_a,reshape_b))
print(concat)

[[1 2]
 [3 4]]
................
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [175]:
#UNIVERSAL FUNCTIONS
a = np.array([1, 4, 9, 16])

sqrt = np.sqrt(a)
print(sqrt)
print(np.exp(a))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [179]:
#AGGREGATION FUNCTION
arr = np.array([1, 2, 3, 4, 5])

total = np.sum(arr)  
print(total)
mean = np.mean(arr)         
std_dev = np.std(arr)       
minimum = np.min(arr)       
maximum = np.max(arr)       


15


In [5]:
a = np.array([[1,2,3],[4,5,6]])
#calc mean along specific axis
mean = np.mean(a,axis=0)
print(mean)
sd = np.std(a,axis=1)
print(sd)

[2.5 3.5 4.5]
[0.81649658 0.81649658]


In [281]:
#RANDOM NUMBERS

float = np.random.rand(2)
print(float)

int = np.random.randint(1,10,size=3)
print(int)

normal = np.random.normal(loc=0,scale=1,size=5)
print(normal)

[0.72584159 0.20313834]
[6 9 5]
[-0.79018262 -0.47095737 -1.68238761 -1.02873501  0.1124824 ]


In [277]:
#RANDOM SAMPLING
a = np.array([10,20,30,40,50])

choice = np.random.choice(a,size=2,replace=True)
print(choice)

permute = np.random.permutation(a)
print(permute)


[10 10]
[20 10 50 30 40]


In [3]:
#PANDAS
import pandas as pd

data = [10,20,30,40]
series = pd.Series(data)
print(series)
print(series[0])



0    10
1    20
2    30
3    40
dtype: int64
10


In [297]:
#DATA FRAME
data = {
    'name':['alice','bob','charlie'],
    'age':[20,30,32],
    'city':['ny','los','chocgo']
}

df = pd.DataFrame(data)
print(df)


      name  age    city
0    alice   20      ny
1      bob   30     los
2  charlie   32  chocgo


In [311]:
print(df['age'])

#integer locaction based indexing
print(df.iloc[0:1])
#label based indexing
print(df.loc[0:1])
      

0    20
1    30
2    32
Name: age, dtype: int64
    name  age city
0  alice   20   ny
    name  age city
0  alice   20   ny
1    bob   30  los


In [313]:
#Boolean Indexing
condn = df[df['age'] > 28]
print(condn)



      name  age    city
1      bob   30     los
2  charlie   32  chocgo


In [331]:
#Data Manipulation
data = {
    'Name': ['Alice', 'Bob', None],
    'Age': [25, None, 35]
}
df = pd.DataFrame(data)
print(df)
print('.......')

remove = df.dropna()
print(remove)

print('.........')

fill = df.fillna({'Name': 'Unknown', 'Age': df['Age'].mean()})
print(fill)
                 
                 




    Name   Age
0  Alice  25.0
1    Bob   NaN
2   None  35.0
.......
    Name   Age
0  Alice  25.0
.........
      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Unknown  35.0


In [344]:
#Remove Duplicates in DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Alice'],
    'Age': [25, 30, 25]
}
df = pd.DataFrame(data)
print(df)

removeDuplicate = df.drop_duplicates()
print('>>>>>>>>')
print(removeDuplicate)




    Name  Age
0  Alice   25
1    Bob   30
2  Alice   25
>>>>>>>>
    Name  Age
0  Alice   25
1    Bob   30


In [5]:
#PIVOT TABLE
import pandas as pd
data = {
    'Salesperson': ['Alice', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob'],
    'Product': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Sales': [200, 150, 300, 200, 250, 100]
}
df = pd.DataFrame(data)
print(df)
print('>>>>>>>>>>>>>>>>>>>>>')


pivot = df.pivot_table(values='Sales',index='Product',columns='Salesperson',aggfunc='sum',fill_value=0)
print(pivot)


  Salesperson Product  Sales
0       Alice       A    200
1         Bob       A    150
2       Alice       B    300
3         Bob       B    200
4       Alice       C    250
5         Bob       C    100
>>>>>>>>>>>>>>>>>>>>>
Salesperson  Alice  Bob
Product                
A              200  150
B              300  200
C              250  100


In [378]:
#SUMMARY STATISTICS

data = {'score':[85, 90, 95, 80, 75, 92, 88]}
df = pd.DataFrame(data)
print(df)
print('<<<<<<<<<<<<<<<')
summary = df.describe()
print(summary)

mean = df.mean()
print(mean)

   score
0     85
1     90
2     95
3     80
4     75
5     92
6     88
<<<<<<<<<<<<<<<
           score
count   7.000000
mean   86.428571
std     6.996598
min    75.000000
25%    82.500000
50%    88.000000
75%    91.000000
max    95.000000
score    86.428571
dtype: float64


In [388]:
#GROUPBY
data = {
    'Department': ['Sales', 'Sales', 'HR', 'HR', 'IT', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 60000, 55000, 48000, 70000, 72000]
}
df = pd.DataFrame(data)
print(df)
print('>>>>>>>>>>>>>>>>>>>>')

group = df.groupby('Department')['Salary'].sum()
print(group)



  Department Employee  Salary
0      Sales    Alice   50000
1      Sales      Bob   60000
2         HR  Charlie   55000
3         HR    David   48000
4         IT      Eve   70000
5         IT    Frank   72000
>>>>>>>>>>>>>>>>>>>>
Department
HR       103000
IT       142000
Sales    110000
Name: Salary, dtype: int64


In [11]:
a = np.array([[10,20,90],[30,40,50]])

for i in np.nditer(a):
    print(i**2)

100
400
8100
900
1600
2500


In [29]:
from scipy.stats import *
a = np.array([78, 82, 75, 70, 68, 80, 85, 77, 73, 79])
mean = np.mean(a)


t,p = ttest_1samp(a,mean)
print(t)
print(p)

0.0
1.0
